# Pairwise choice constants.
MAJOR_A_WIN = "A>>B"
MINOR_A_WIN = "A>B"
MINOR_B_WIN = "B>A"
MAJOR_B_WIN = "B>>A"
TIE = "A=B"

FIVE_POINT_SCALE = [MAJOR_A_WIN, MINOR_A_WIN, TIE, MINOR_B_WIN, MAJOR_B_WIN]
FOUR_POINT_SCALE = [MAJOR_A_WIN, MINOR_A_WIN, MINOR_B_WIN, MAJOR_B_WIN]
THREE_POINT_SCALE = [MINOR_A_WIN, TIE, MINOR_B_WIN]
TWO_POINT_SCALE = [MINOR_A_WIN, MINOR_B_WIN]
